require:
  - "rubocop-rails"
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/bundle"
Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: true
